package com.mycompany.a3;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.Toolbar;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
/*
 * This is the start point for the game. Use 'Run as' and select option for codenameone simulator.
 * Current design best played on tablet simulator skins
 * 
 * Basic MVC architecture
 * 
 * Game - Controller
 * GameWorld - Model
 * MapView and PointsView - Views
 */
public class Starter {

    private Form current;
    
    public void init(Object context) {
        UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        
        new Game(); //Construct instance of Game Class, the controller 
    }
    

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
